version: '3.8'

services:
  orders:
    image: node:16-alpine3.12
    container_name: orders
    env_file: .env
    ports:
      - $MAIN_PORT:$MAIN_PORT
    volumes:
      - './:/app'
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run start:main
  delivery:
    image: node:16-alpine3.12
    container_name: delivery
    env_file: .env
    ports:
      - $PORT_1:$PORT_1
    volumes:
      - './:/app'
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run start:delivery
  notification:
    image: node:16-alpine3.12
    container_name: notification
    env_file: .env
    ports:
      - $PORT_2:$PORT_2
    volumes:
      - './:/app'
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run start:notification